print("Homework-2 Task-2")
print("this easy program put symbol *,* between two words")
firstw = input("Please write first word: ")
secondw = input("Please write second word: ")
print(firstw, ",", secondw)